name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint anybadge
    - name: Analysing the code with pylint
      run: |
        pylint pi_server/ | tee pylint.txt
        score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
        anybadge -l pylint -v $score -f pylint.svg 2=red 4=orange 9=yellow 10=green
    - name: Archive code coverage results
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update pylint badge
        branch: badges
        commit_options: '--no-verify --signoff'
        file_pattern: '*.svg '
        create_branch: true
        push_options: '--force'

